# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zin Mag
tagline:          'Stories of Web development'
description:      ''
url:              
baseurl:          /

author:
  name:           'Zin'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
